export const AIRPORTS: { city: string; code: string; continent: string }[] = [
  { city: "Amsterdam", code: "AMS", continent: "Europe" },
  { city: "Athens", code: "ATH", continent: "Europe" },
  { city: "Antwerp", code: "ANR", continent: "Europe" },
  { city: "Barcelona", code: "BCN", continent: "Europe" },
  { city: "Berlin", code: "BER", continent: "Europe" },
  { city: "Brussels", code: "BRU", continent: "Europe" },
  { city: "Copenhagen", code: "CPH", continent: "Europe" },
  { city: "Dublin", code: "DUB", continent: "Europe" },
  { city: "Frankfurt", code: "FRA", continent: "Europe" },
  { city: "Geneva", code: "GVA", continent: "Europe" },
  { city: "Lisbon", code: "LIS", continent: "Europe" },
  { city: "London", code: "LHR", continent: "Europe" },
  { city: "Madrid", code: "MAD", continent: "Europe" },
  { city: "Milan", code: "MXP", continent: "Europe" },
  { city: "Munich", code: "MUC", continent: "Europe" },
  { city: "Oslo", code: "OSL", continent: "Europe" },
  { city: "Paris", code: "CDG", continent: "Europe" },
  { city: "Prague", code: "PRG", continent: "Europe" },
  { city: "Rome", code: "FCO", continent: "Europe" },
  { city: "Stockholm", code: "ARN", continent: "Europe" },
  { city: "Vienna", code: "VIE", continent: "Europe" },
  { city: "Warsaw", code: "WAW", continent: "Europe" },
  { city: "Zurich", code: "ZRH", continent: "Europe" },
  { city: "Atlanta", code: "ATL", continent: "North America" },
  { city: "Austin", code: "AUS", continent: "North America" },
  { city: "Boston", code: "BOS", continent: "North America" },
  { city: "Chicago", code: "ORD", continent: "North America" },
  { city: "Dallas", code: "DFW", continent: "North America" },
  { city: "Denver", code: "DEN", continent: "North America" },
  { city: "Los Angeles", code: "LAX", continent: "North America" },
  { city: "Miami", code: "MIA", continent: "North America" },
  { city: "Montreal", code: "YUL", continent: "North America" },
  { city: "New York", code: "JFK", continent: "North America" },
  { city: "San Francisco", code: "SFO", continent: "North America" },
  { city: "Toronto", code: "YYZ", continent: "North America" },
  { city: "Vancouver", code: "YVR", continent: "North America" },
  { city: "Washington", code: "IAD", continent: "North America" },
  { city: "Buenos Aires", code: "EZE", continent: "South America" },
  { city: "Bogota", code: "BOG", continent: "South America" },
  { city: "Lima", code: "LIM", continent: "South America" },
  { city: "Rio de Janeiro", code: "GIG", continent: "South America" },
  { city: "Santiago", code: "SCL", continent: "South America" },
  { city: "Sao Paulo", code: "GRU", continent: "South America" },
  { city: "Abu Dhabi", code: "AUH", continent: "Asia" },
  { city: "Bangkok", code: "BKK", continent: "Asia" },
  { city: "Beijing", code: "PEK", continent: "Asia" },
  { city: "Delhi", code: "DEL", continent: "Asia" },
  { city: "Doha", code: "DOH", continent: "Asia" },
  { city: "Dubai", code: "DXB", continent: "Asia" },
  { city: "Hong Kong", code: "HKG", continent: "Asia" },
  { city: "Istanbul", code: "IST", continent: "Asia" },
  { city: "Jakarta", code: "CGK", continent: "Asia" },
  { city: "Kuala Lumpur", code: "KUL", continent: "Asia" },
  { city: "Manila", code: "MNL", continent: "Asia" },
  { city: "Mumbai", code: "BOM", continent: "Asia" },
  { city: "Osaka", code: "KIX", continent: "Asia" },
  { city: "Seoul", code: "ICN", continent: "Asia" },
  { city: "Singapore", code: "SIN", continent: "Asia" },
  { city: "Tokyo", code: "NRT", continent: "Asia" },
  { city: "Accra", code: "ACC", continent: "Africa" },
  { city: "Addis Ababa", code: "ADD", continent: "Africa" },
  { city: "Cairo", code: "CAI", continent: "Africa" },
  { city: "Cape Town", code: "CPT", continent: "Africa" },
  { city: "Casablanca", code: "CMN", continent: "Africa" },
  { city: "Johannesburg", code: "JNB", continent: "Africa" },
  { city: "Lagos", code: "LOS", continent: "Africa" },
  { city: "Nairobi", code: "NBO", continent: "Africa" },
  { city: "Auckland", code: "AKL", continent: "Oceania" },
  { city: "Brisbane", code: "BNE", continent: "Oceania" },
  { city: "Melbourne", code: "MEL", continent: "Oceania" },
  { city: "Perth", code: "PER", continent: "Oceania" },
  { city: "Sydney", code: "SYD", continent: "Oceania" },
];

export function matchAirports(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const matches = AIRPORTS.filter((a) => a.city.toLowerCase().startsWith(q));
  const byContinent = new Map<string, typeof AIRPORTS>();
  for (const m of matches) {
    if (!byContinent.has(m.continent)) byContinent.set(m.continent, []);
    byContinent.get(m.continent)!.push(m);
  }
  return Array.from(byContinent.entries());
}
