export const AIRPORTS: { city: string; code: string; continent: string; country: string }[] = [
  { city: "Amsterdam", code: "AMS", continent: "Europe", country: "Netherlands" },
  { city: "Athens", code: "ATH", continent: "Europe", country: "Greece" },
  { city: "Antwerp", code: "ANR", continent: "Europe", country: "Belgium" },
  { city: "Barcelona", code: "BCN", continent: "Europe", country: "Spain" },
  { city: "Berlin", code: "BER", continent: "Europe", country: "Germany" },
  { city: "Brussels", code: "BRU", continent: "Europe", country: "Belgium" },
  { city: "Copenhagen", code: "CPH", continent: "Europe", country: "Denmark" },
  { city: "Dublin", code: "DUB", continent: "Europe", country: "Ireland" },
  { city: "Frankfurt", code: "FRA", continent: "Europe", country: "Germany" },
  { city: "Geneva", code: "GVA", continent: "Europe", country: "Switzerland" },
  { city: "Lisbon", code: "LIS", continent: "Europe", country: "Portugal" },
  { city: "London", code: "LHR", continent: "Europe", country: "United Kingdom" },
  { city: "Madrid", code: "MAD", continent: "Europe", country: "Spain" },
  { city: "Milan", code: "MXP", continent: "Europe", country: "Italy" },
  { city: "Munich", code: "MUC", continent: "Europe", country: "Germany" },
  { city: "Oslo", code: "OSL", continent: "Europe", country: "Norway" },
  { city: "Paris", code: "CDG", continent: "Europe", country: "France" },
  { city: "Prague", code: "PRG", continent: "Europe", country: "Czech Republic" },
  { city: "Rome", code: "FCO", continent: "Europe", country: "Italy" },
  { city: "Stockholm", code: "ARN", continent: "Europe", country: "Sweden" },
  { city: "Vienna", code: "VIE", continent: "Europe", country: "Austria" },
  { city: "Warsaw", code: "WAW", continent: "Europe", country: "Poland" },
  { city: "Zurich", code: "ZRH", continent: "Europe", country: "Switzerland" },
  { city: "Atlanta", code: "ATL", continent: "North America", country: "United States" },
  { city: "Austin", code: "AUS", continent: "North America", country: "United States" },
  { city: "Boston", code: "BOS", continent: "North America", country: "United States" },
  { city: "Chicago", code: "ORD", continent: "North America", country: "United States" },
  { city: "Dallas", code: "DFW", continent: "North America", country: "United States" },
  { city: "Denver", code: "DEN", continent: "North America", country: "United States" },
  { city: "Los Angeles", code: "LAX", continent: "North America", country: "United States" },
  { city: "Miami", code: "MIA", continent: "North America", country: "United States" },
  { city: "Montreal", code: "YUL", continent: "North America", country: "Canada" },
  { city: "New York", code: "JFK", continent: "North America", country: "United States" },
  { city: "San Francisco", code: "SFO", continent: "North America", country: "United States" },
  { city: "Toronto", code: "YYZ", continent: "North America", country: "Canada" },
  { city: "Vancouver", code: "YVR", continent: "North America", country: "Canada" },
  { city: "Washington", code: "IAD", continent: "North America", country: "United States" },
  { city: "Buenos Aires", code: "EZE", continent: "South America", country: "Argentina" },
  { city: "Bogota", code: "BOG", continent: "South America", country: "Colombia" },
  { city: "Lima", code: "LIM", continent: "South America", country: "Peru" },
  { city: "Rio de Janeiro", code: "GIG", continent: "South America", country: "Brazil" },
  { city: "Santiago", code: "SCL", continent: "South America", country: "Chile" },
  { city: "Sao Paulo", code: "GRU", continent: "South America", country: "Brazil" },
  { city: "Abu Dhabi", code: "AUH", continent: "Asia", country: "United Arab Emirates" },
  { city: "Bangkok", code: "BKK", continent: "Asia", country: "Thailand" },
  { city: "Beijing", code: "PEK", continent: "Asia", country: "China" },
  { city: "Delhi", code: "DEL", continent: "Asia", country: "India" },
  { city: "Doha", code: "DOH", continent: "Asia", country: "Qatar" },
  { city: "Dubai", code: "DXB", continent: "Asia", country: "United Arab Emirates" },
  { city: "Hong Kong", code: "HKG", continent: "Asia", country: "Hong Kong" },
  { city: "Istanbul", code: "IST", continent: "Asia", country: "Turkey" },
  { city: "Jakarta", code: "CGK", continent: "Asia", country: "Indonesia" },
  { city: "Kuala Lumpur", code: "KUL", continent: "Asia", country: "Malaysia" },
  { city: "Manila", code: "MNL", continent: "Asia", country: "Philippines" },
  { city: "Mumbai", code: "BOM", continent: "Asia", country: "India" },
  { city: "Osaka", code: "KIX", continent: "Asia", country: "Japan" },
  { city: "Seoul", code: "ICN", continent: "Asia", country: "South Korea" },
  { city: "Singapore", code: "SIN", continent: "Asia", country: "Singapore" },
  { city: "Tokyo", code: "NRT", continent: "Asia", country: "Japan" },
  { city: "Accra", code: "ACC", continent: "Africa", country: "Ghana" },
  { city: "Addis Ababa", code: "ADD", continent: "Africa", country: "Ethiopia" },
  { city: "Cairo", code: "CAI", continent: "Africa", country: "Egypt" },
  { city: "Cape Town", code: "CPT", continent: "Africa", country: "South Africa" },
  { city: "Casablanca", code: "CMN", continent: "Africa", country: "Morocco" },
  { city: "Johannesburg", code: "JNB", continent: "Africa", country: "South Africa" },
  { city: "Lagos", code: "LOS", continent: "Africa", country: "Nigeria" },
  { city: "Nairobi", code: "NBO", continent: "Africa", country: "Kenya" },
  { city: "Auckland", code: "AKL", continent: "Oceania", country: "New Zealand" },
  { city: "Brisbane", code: "BNE", continent: "Oceania", country: "Australia" },
  { city: "Melbourne", code: "MEL", continent: "Oceania", country: "Australia" },
  { city: "Perth", code: "PER", continent: "Oceania", country: "Australia" },
  { city: "Sydney", code: "SYD", continent: "Oceania", country: "Australia" },
];

export function matchAirports(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const matches = AIRPORTS.filter(
    (a) => a.city.toLowerCase().startsWith(q) || a.country.toLowerCase().startsWith(q)
  );
  const byContinent = new Map<string, typeof AIRPORTS>();
  for (const m of matches) {
    if (!byContinent.has(m.continent)) byContinent.set(m.continent, []);
    byContinent.get(m.continent)!.push(m);
  }
  return Array.from(byContinent.entries());
}
